#!/usr/bin/env python3

import os

vendor = "157239n"
images = ["basic", "apache", "php", "php7.0", "mysql", "mysql7.0", "proxy", "nginx"]

for image in images:
	os.system("docker image build --tag " + vendor + "/" + image + " " + image + "/")
